name = "blackhole-site"
main = "src/worker.js"
compatibility_date = "2025-11-12"

[assets]
directory = "./public"
binding = "ASSETS"

[durable_objects]
bindings = [
  { name = "RateLimiterDurableObject", class_name = "RateLimiterDurableObject" }
]

